addSbtPlugin("ch.epfl.scala"  % "sbt-bloop"      % "2.0.19")
// addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.10.1")
//addSbtPlugin("com.typesafe"  % "sbt-mima-plugin" % "1.1.5")
// addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"  % "0.13.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.6.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"       % "2.9.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")

addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.7.5")
