//addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.2")

addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"                 % "1.4.8")
addSbtPlugin("com.typesafe"     % "sbt-mima-plugin"           % "0.8.1")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"             % "0.10.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.9.27")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"                  % "2.2.20")
addSbtPlugin("com.geirsson"     % "sbt-ci-release"            % "1.5.7")
