addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"                 % "1.5.2")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.10.1")
addSbtPlugin("com.typesafe"     % "sbt-mima-plugin"           % "1.1.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"             % "0.11.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.4.6")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"                  % "2.3.2")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"            % "1.5.10")

addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.4.6")
